---
- name: configure_satisfactory - Create directory {{ _satisfactory_config_dir }}
  ansible.builtin.file:
    path: "{{ _satisfactory_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ satisfactory_user }}"
    group: "{{ satisfactory_user }}"

- name: configure_satisfactory - Deploy config files to {{ _satisfactory_config_dir }}
  ansible.builtin.template:
    src: satisfactory/{{ item }}
    dest: "{{ _satisfactory_config_dir }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - Engine.ini
    - Game.ini
    - Scalability.ini
    - ServerSettings.ini
  register: _satisfactory_config_file_register
