---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: Include "configure_{{ ansible_pkg_mgr }}.yml"
  ansible.builtin.include_tasks: "{{ item }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - configure_{{ ansible_pkg_mgr }}.yml
      skip: true

- ansible.builtin.include_tasks: create_user.yml
- ansible.builtin.include_tasks: install.yml
- ansible.builtin.include_tasks: configure_satisfactory.yml
- ansible.builtin.include_tasks: configure_service.yml
